### ISSUE TITLE
Missing file content?

### ISSUE THREAD

**Issue by gpwolfe** [zpengmei/xxMD#1]
I have just downloaded and unzipped the dataset files for xxMD-CASSCF and xxMD-DFT, and there appear to be five files that have missing or corrupted contents. I've tried re-downloading, but the problem persists.
The files in xxMD-CASSCF are:
* sti_train_s2.xyz
* sti_val_s0.xyz
* sti_val_s1.xyz
* sti_val_s2.xyz  

And in xxMD-DFT, the file is:
* sti_train_uks.xyz

**Comment by gpwolfe** [comment]
The end of the file xxMD-main/xxMD-CASSCF/sti/s1/sti_s1/sti_train_s1.xyz also appears to be corrupted, as well

**Comment by zpengmei** [comment]
Should be fixed now? I just re-uploaded those stilbene files and tested on another computer. Thanks for spotting that!

**Comment by gpwolfe** [comment]
Perfect, thank you! Tested and working.
